service: screenshot-service

provider:
  name: aws
  region: ap-south-1
  stage: prod
  runtime: nodejs14.x
  memorySize: 3008
  timeout: 100
  environment:
    LOCAL: ${env:LOCAL}

functions:
  png:
    handler: src/handler.default
    events:
    - http:
        path: /
        method: get

plugins:
  - serverless-apigw-binary
  - serverless-offline
  - serverless-webpack

custom:
  serverless-offline:
    port: 4000
    noTimeout: true
  apigwBinary:
    types:
    - '*/*'
  webpack:
    includeModules:
      forceExclude:
        - puppeteer
    packager: 'yarn'
